### ISSUE TITLE
nikke联动nier最新立绘

### ISSUE THREAD

**Issue by taocanxingzi** [Koshirei/Koshirei.github.io#1]

**Comment by Koshirei** [comment]
Don't make tickets about nikke db on any repositories beside the website's. Why did you went in my portfolio for a request ?

I cannot understand what've you wrote, use english next time please, I used a translator for the question, future ones will be ignored.

Nier Nikke patch released at midnight and I had to wake up at 6:30 am for work. It is currently 7:36 am and I'm in the train toward my 8 hours shift. I couldn't work on an update already and preferred getting some sleep.

On a side note, it is currently impossible to update nikke-db as the developpers updated their nkab encryption and the tool I used became a paid only software with a ridiculous price tag. All this due to pityful mod stealings by people I've never heard of.

I cannot make any estimate of when it'll be updated.

Tout vient à point à qui sait attendre.

**Comment by taocanxingzi** [comment]
Okay, I'm sorry about that. I'm not very familiar with Github. I think this dialog box can be used to contact the author. The machine translation is not very accurate, and in order to avoid contacting you in the wrong place, I would like you to provide me with your email or other contact information for future updates. I appreciate the website you created. This has brought me great convenience. I saw you say in the conversation that you were busy with work, and I apologize again for my mistake Please pay attention to your body

**Comment by Koshirei** [comment]
It's fine. I am indeed the creator of nikke-db but it is common practice to open issues on a project's repository to get in touch with developpers or when you find bugs. for nikke-db the repository is https://github.com/Nikke-db/Nikke-db.github.io , but I'm sure you've found it already if you managed to find my github account.  

This is my personal portfolio that was used to be sent to schools and jobs to have a web resume about myself, as such it has nothing to do with nikke or any other of my projects.

Nikke have an encrypted folder which we could access, but the latest patch changed the encryption and for now no website can retrieve any important files from the game. Nikke-db will stay in stand by until then, I'll add a message later today.
